### ISSUE TITLE
Add ability to disable showing the menu on shake

### ISSUE THREAD

**Issue by sethcwhiting** [GleapSDK/ReactNative-SDK#1]
Hey thanks for making this! It's super helpful/useful.

One request:
We have a button on our app that makes use of the `Gleap.open()` functionality, and would prefer to **only** use that and not make use of the "shake device to open menu" functionality. Would it be possible to get that in an update?

(P.S. My apologies if this is already possible and I just missed it.)

**Comment by boehlerlukas** [comment]
Hey @sethcwhiting !

Sorry for the late reply. This is possible already :) Simply open your project in the Gleap dashboard and navigate to "Widget configuration" -> "Advanced" and then select "App SDK". Now you can enable and disable the activation methods.

In addition to that we will also add methods to enable & disable these options programmatically within the next few days.

<img width="1509" alt="Bildschirmfoto 2022-03-13 um 11 22 19" src="https://user-images.githubusercontent.com/5601888/158073637-8d2aa8ef-fcf0-4624-88e8-9af43e1167c6.png">

**Comment by sethcwhiting** [comment]
@boehlerlukas Thanks so much! I'll go flip that switch!

**Comment by boehlerlukas** [comment]
@sethcwhiting Awesome! I will let you know once we also implemented the methods for manual overwriting these settings.

**Comment by seemX17** [comment]
When I disable the switch I can still see the shake gesture working

**Comment by boehlerlukas** [comment]
Hey @seemX17 :)

After turning the switch off and saving, you will need to restart the app. You might also want to try turning it on /off once more, just to make sure it's not some sort of caching issue. (the config needs to reload).

Let me know if it still doesn't work :)

**Comment by seemX17** [comment]
We are using react-native-gleapsdk:13.1.1 and it doesn't seem to work both on Android and ios @boehlerlukas

**Comment by boehlerlukas** [comment]
@seemX17 thanks for the update! We will look into it right tomorrow morning :) Will update you asap.

**Comment by boehlerlukas** [comment]
Hey @seemX17 ,

Could you try with the new RN release (v13.2.1). We were actually not able to reproduce the issue on Android (we tested on multiple phones).

Also please make sure to run pod install --repo-update and update gradle to get the latest native dependencies :)

**Comment by seemX17** [comment]
Hi @boehlerlukas , 
It is possible that this bug occurs because we have two different tokens. 
The flow is the following
Open the app -> User is not logged in -> initialized with a projectA token
User logs in -> Initialized with  projectB token
This scenario works fine on iOS .
Is there a systematic way to reset with a new token?

**Comment by boehlerlukas** [comment]
Hey @seemX17

That might be the case - it's actually not even fully supported doing the initialization twice - this usually leads to more issues etc.
Could you test if it works if you don't do this? Also: could you share some more details on why you need to have two different projects for logged in / logged out? Usually it's easier to manage to have one project in that scenario :) A lot of the content can be adjusted based on audience rules.

Happy to hear back from you :)

**Comment by seemX17** [comment]
It works if we have only one initialization. In the app, there are two different companies and they want their respective Gleap accounts hence the two different projects.
One is general and the other account is company-specific so we need two different projects.  @boehlerlukas
